# Generated by Django 5.2.8 on 2025-11-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('guardian_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('course_completion_date', models.DateField(blank=True, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student_photo', models.FileField(blank=True, null=True, upload_to='student_photos/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.course')),
            ],
        ),
    ]
