# Generated by Django 5.2.8 on 2025-11-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_ledgerentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LedgerEntry',
            new_name='Transaction',
        ),
    ]
