# Generated by Django 5.2.8 on 2025-11-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_ledgerentry_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_form',
            field=models.FileField(blank=True, null=True, upload_to='admission_forms/'),
        ),
    ]
