# Generated by Django 5.2.8 on 2025-11-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_student_address_student_admission_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
