# Generated by Django 5.2.8 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='referee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='referee_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
